export const $ = (selector, parent = document) => parent.querySelector(selector);
export const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];

export const elements = Object.freeze({
  goalForm: $('#goalForm'),
  recordForm: $('#recordForm'),
  startLevel: $('#startLevel'),
  startExp: $('#startExp'),
  targetLevel: $('#targetLevel'),
  burningModeInputs: $$('input[name="burningMode"]'),
  targetTime: $('#targetTime'),
  dailyTrainingHours: $('#dailyTrainingHours'),
  recordDate: $('#recordDate'),
  endLevel: $('#endLevel'),
  endExp: $('#endExp'),
  minutes: $('#minutes'),
  note: $('#note'),
  currentProgress: $('#currentProgress'),
  currentTotalExp: $('#currentTotalExp'),
  remainingExp: $('#remainingExp'),
  completeRate: $('#completeRate'),
  progressFill: $('#progressFill'),
  totalMinutes: $('#totalMinutes'),
  recordCount: $('#recordCount'),
  avgPerHour: $('#avgPerHour'),
  averageDailyHours: $('#averageDailyHours'),
  averageDailyHourStatus: $('#averageDailyHourStatus'),
  estimateTime: $('#estimateTime'),
  projectedFinishDate: $('#projectedFinishDate'),
  projectedFinishStatus: $('#projectedFinishStatus'),
  totalExpProjectedFinishDate: $('#totalExpProjectedFinishDate'),
  totalExpProjectedFinishStatus: $('#totalExpProjectedFinishStatus'),
  requiredSpeed: $('#requiredSpeed'),
  speedStatus: $('#speedStatus'),
  requiredDailyHours: $('#requiredDailyHours'),
  dailyHourStatus: $('#dailyHourStatus'),
  recordList: $('#recordList'),
  recordRowTemplate: $('#recordRowTemplate'),
  recordDetailTemplate: $('#recordDetailTemplate'),
  emptyRecordTemplate: $('#emptyRecordTemplate'),
  clearRecordsButton: $('#clearRecordsButton'),
  resetAllButton: $('#resetAllButton'),
  clearRecordFormButton: $('#clearRecordFormButton'),
  fillDefaultGoalButton: $('#fillDefaultGoalButton'),
  deviceMode: $('#deviceMode'),
  storageModeBadge: $('#storageModeBadge'),
  storageChoiceModal: $('#storageChoiceModal'),
  storageModalCloseButton: $('#storageModalCloseButton'),
  useBrowserStorageButton: $('#useBrowserStorageButton'),
  createFileStorageButton: $('#createFileStorageButton'),
  openFileStorageButton: $('#openFileStorageButton'),
  changeStorageButton: $('#changeStorageButton'),
  exportBackupButton: $('#exportBackupButton'),
  importBackupButton: $('#importBackupButton'),
  importBackupInput: $('#importBackupInput'),
  goalSaveStatus: $('#goalSaveStatus'),
  toast: $('#toast'),
});
