// ===========================
// 閃亮彗星（Sparkling）
// ===========================
const sparklingItems = [
  // 🔹 A
  { name: "甜蜜浪漫管家髮飾", type: "A", chance: 1.00, gender: null },
  { name: "甜蜜純情女僕髮飾", type: "A", chance: 1.00, gender: null },
  { name: "甜蜜浪漫管家西裝", type: "A", chance: 0.85, gender: null },
  { name: "甜蜜純情女僕洋裝", type: "A", chance: 0.85, gender: null },
  { name: "甜蜜浪漫管家鞋子", type: "A", chance: 1.10, gender: null },
  { name: "甜蜜純情女僕鞋子", type: "A", chance: 1.10, gender: null },
  { name: "甜蜜的浪漫派",     type: "A", chance: 0.80, gender: null },
  { name: "甜蜜的純情派",     type: "A", chance: 0.75, gender: null },

  // 🔹 B
  { name: "冰藍夢幻蕾絲頭飾",     type: "B", chance: 1.40, gender: null },
  { name: "玫瑰紅夢幻蕾絲頭飾",   type: "B", chance: 1.40, gender: null },
  { name: "柔軟搖籃曲(男)",       type: "B", chance: 1.30, gender: "male" },
  { name: "心動搖籃曲(女)",       type: "B", chance: 1.30, gender: "female" }, // 推定同組 1.30
  { name: "冰藍紙娃娃鞋",         type: "B", chance: 1.45, gender: null },
  { name: "玫瑰紅紙娃娃鞋",       type: "B", chance: 1.45, gender: null },
  { name: "紙上談夢",             type: "B", chance: 1.35, gender: null },
  { name: "紙娃娃之翼",           type: "B", chance: 1.35, gender: null },
  { name: "珍愛的夢幻兔子",       type: "B", chance: 1.00, gender: null },

  // 🔹 C（皆 1.22）
  { name: "深粉色明星帽子", type: "C", chance: 1.22, gender: null },
  { name: "淡粉色明星帽子", type: "C", chance: 1.22, gender: null },
  { name: "藍天格紋嘻哈帽", type: "C", chance: 1.22, gender: null },
  { name: "少林金人頭套", type: "C", chance: 1.22, gender: null },
  { name: "貍貓帽", type: "C", chance: 1.22, gender: null },
  { name: "蕾絲珍珠髮圈", type: "C", chance: 1.22, gender: null },
  { name: "長嘴鳥巢頭", type: "C", chance: 1.22, gender: null },
  { name: "瑪西帽", type: "C", chance: 1.22, gender: null },
  { name: "章魚啾啾帽", type: "C", chance: 1.22, gender: null },
  { name: "容貌偽裝", type: "C", chance: 1.22, gender: null },
  { name: "粉紅腮紅", type: "C", chance: 1.22, gender: null },
  { name: "粉藍腮紅", type: "C", chance: 1.22, gender: null },
  { name: "聖誕鬍子", type: "C", chance: 1.22, gender: null },
  { name: "紅鼻子", type: "C", chance: 1.22, gender: null },
  { name: "綠色遮陽眼鏡", type: "C", chance: 1.22, gender: null },
  { name: "紅色流氓面具", type: "C", chance: 1.22, gender: null },
  { name: "綠色眼鏡", type: "C", chance: 1.22, gender: null },
  { name: "深粉色明星套服", type: "C", chance: 1.22, gender: null },
  { name: "淡粉色明星套服", type: "C", chance: 1.22, gender: null },
  { name: "五星吊帶褲", type: "C", chance: 1.22, gender: null },
  { name: "小精靈服裝", type: "C", chance: 1.22, gender: null },
  { name: "鉚釘扣大衣", type: "C", chance: 1.22, gender: null },
  { name: "日系背心短褲套裝", type: "C", chance: 1.22, gender: null },
  { name: "藍色水手服", type: "C", chance: 1.22, gender: null },
  { name: "潛水服", type: "C", chance: 1.22, gender: null },
  { name: "紅圍領T恤", type: "C", chance: 1.22, gender: null },
  { name: "台客古惑上衣", type: "C", chance: 1.22, gender: null },
  { name: "紫色流星無袖T恤", type: "C", chance: 1.22, gender: null },
  { name: "避暑格子襯衫", type: "C", chance: 1.22, gender: null },
  { name: "閃亮運動上衣", type: "C", chance: 1.22, gender: null },
  { name: "小可愛星星上衣", type: "C", chance: 1.22, gender: null },
  { name: "星星T恤-黃色", type: "C", chance: 1.22, gender: null },
  { name: "紅色連帽坎肩", type: "C", chance: 1.22, gender: null },
  { name: "櫻桃運動上衣", type: "C", chance: 1.22, gender: null },
  { name: "勝者籃球上衣", type: "C", chance: 1.22, gender: null },
  { name: "紅色街舞褲", type: "C", chance: 1.22, gender: null },
  { name: "綠方格紅褲", type: "C", chance: 1.22, gender: null },
  { name: "桃紅漸層褲", type: "C", chance: 1.22, gender: null },
  { name: "灰色格紋短褲", type: "C", chance: 1.22, gender: null },
  { name: "紅腰帶褲裙", type: "C", chance: 1.22, gender: null },
  { name: "造型海灘褲", type: "C", chance: 1.22, gender: null },
  { name: "橄欖色貼身牛仔褲", type: "C", chance: 1.22, gender: null },
  { name: "綠色冒險褲", type: "C", chance: 1.22, gender: null },
  { name: "粉紅夏威夷短褲", type: "C", chance: 1.22, gender: null },
  { name: "小白兔紅色褲子", type: "C", chance: 1.22, gender: null },
  { name: "森林鞋", type: "C", chance: 1.22, gender: null },
  { name: "環島旅行咕咕拖", type: "C", chance: 1.22, gender: null },
  { name: "甜蜜粉紅翅膀", type: "C", chance: 1.22, gender: null },
  { name: "藍色圓點拖鞋", type: "C", chance: 1.22, gender: null },
  { name: "藍色潛水鞋", type: "C", chance: 1.22, gender: null },
  { name: "揹雪人", type: "C", chance: 1.22, gender: null },
  { name: "愛你唷!巧克力氣球", type: "C", chance: 1.22, gender: null },
  { name: "煉獄巫師披風", type: "C", chance: 1.22, gender: null },
  { name: "惡魔化翅膀", type: "C", chance: 1.22, gender: null },
  { name: "藍星星披風", type: "C", chance: 1.22, gender: null },
  { name: "狗尾巴（黑色）", type: "C", chance: 1.22, gender: null },
  { name: "蝙蝠翅膀", type: "C", chance: 1.22, gender: null },
  { name: "花束", type: "C", chance: 1.22, gender: null },
  { name: "溫莉的樹葉", type: "C", chance: 1.22, gender: null },
  { name: "紅色薔薇", type: "C", chance: 1.22, gender: null },
  { name: "幸福青鳥", type: "C", chance: 1.22, gender: null },
  { name: "花蝴蝶之杖", type: "C", chance: 1.22, gender: null },
  { name: "醜小鴨", type: "C", chance: 1.22, gender: null },
  { name: "櫻花盛開時", type: "C", chance: 1.22, gender: null },
  { name: "我愛紅蘿蔔", type: "C", chance: 1.22, gender: null },
  { name: "飛舞的花朵", type: "C", chance: 1.22, gender: null },
  { name: "人偶師的詛咒", type: "C", chance: 1.22, gender: null },
];


// ===========================
// 璀璨彗星（Brilliant）
// ===========================
const brilliantItems = [
  // 🔹 S
  { name: "宴會的黃金王冠", type: "S", chance: 1.19, gender: null },
  { name: "宴會的黃金髮夾", type: "S", chance: 1.19, gender: null },
  { name: "宴會主角套服",   type: "S", chance: 1.13, gender: null },
  { name: "宴會之花禮服",   type: "S", chance: 1.13, gender: null },
  { name: "宴會主角鞋子",   type: "S", chance: 1.38, gender: null },
  { name: "宴會之花鞋子",   type: "S", chance: 1.38, gender: null },
  { name: "宴會聚光燈",     type: "S", chance: 1.24, gender: null },
  { name: "宴會的皇家手杖", type: "S", chance: 0.86, gender: null },
  { name: "宴會的華麗扇子", type: "S", chance: 0.86, gender: null },

  // 🔹 A（星光/月、襪子/銀河/星/劍）
  { name: "夢幻星光", type: "A", chance: 1.03, gender: null },
  { name: "夢幻新月", type: "A", chance: 1.03, gender: null },
  { name: "夢幻星光收藏家(男)", type: "A", chance: 1.00, gender: "male" },
  { name: "夢幻新月收藏家(女)", type: "A", chance: 1.00, gender: "female" },
  { name: "夢鄉襪子",   type: "A", chance: 1.05, gender: null },
  { name: "星星國襪子", type: "A", chance: 1.05, gender: null },
  { name: "夢幻銀河",   type: "A", chance: 0.99, gender: null },
  { name: "夢之星",     type: "A", chance: 0.97, gender: null },
  { name: "騎士之長劍", type: "A", chance: 0.97, gender: null },

  // 🔹 B（蜜蜂）
  { name: "堅持不拔的蜜蜂帽子", type: "B", chance: 1.69, gender: null },
  { name: "勤奮小蜜蜂帽子",     type: "B", chance: 1.69, gender: null },
  { name: "堅持不放棄的蜜蜂套服", type: "B", chance: 1.65, gender: null },
  { name: "勤奮小蜜蜂套服",       type: "B", chance: 1.65, gender: null },
  { name: "堅持不放棄的蜜蜂鞋子", type: "B", chance: 1.69, gender: null },
  { name: "勤奮的蜜蜂鞋子",       type: "B", chance: 1.69, gender: null },
  { name: "毒針蜜蜂翅膀",         type: "B", chance: 1.69, gender: null },
  { name: "蜜蜂的蜂蜜棒",         type: "B", chance: 1.59, gender: null },
  { name: "蜜蜂的向日葵耳環",     type: "B", chance: 1.68, gender: null },

  // 🔹 A（絕望）
  { name: "絕望面罩", type: "A", chance: 1.03, gender: null },
  { name: "絕望蕾絲", type: "A", chance: 1.03, gender: null },
  { name: "寧靜的絕望(男)", type: "A", chance: 1.00, gender: "male" },
  { name: "純粹的絕望(女)", type: "A", chance: 1.00, gender: "female" },
  { name: "如履荊棘(男)",   type: "A", chance: 1.06, gender: "male" },
  { name: "荊棘叢(女)",     type: "A", chance: 1.06, gender: "female" },
  { name: "褪色的絕望",     type: "A", chance: 1.00, gender: null },
  { name: "懸吊的絕望",     type: "A", chance: 1.00, gender: null },
  { name: "繚繞的仇恨",     type: "A", chance: 0.97, gender: null },
  { name: "絕望治療師",     type: "A", chance: 0.97, gender: null },

  // 🔹 B（恐龍）
  { name: "可愛恐龍帽子",     type: "B", chance: 1.69, gender: null },
  { name: "清爽恐龍帽子",     type: "B", chance: 1.69, gender: null },
  { name: "可愛恐龍套服",     type: "B", chance: 1.65, gender: null },
  { name: "清爽恐龍套服",     type: "B", chance: 1.65, gender: null },
  { name: "可愛恐龍鞋子",     type: "B", chance: 1.69, gender: null },
  { name: "清爽恐龍鞋子",     type: "B", chance: 1.69, gender: null },
  { name: "可愛清爽恐龍披風", type: "B", chance: 1.64, gender: null },
  { name: "可愛清爽恐龍武器", type: "B", chance: 1.59, gender: null },

  // 🔹 A（熾天使）
  { name: "純潔熾天使",               type: "A", chance: 1.05, gender: null },
  { name: "聖潔熾天使",               type: "A", chance: 1.05, gender: null },
  { name: "榮耀熾天使(男)",           type: "A", chance: 1.02, gender: "male" },
  { name: "神聖熾天使(女)",           type: "A", chance: 1.02, gender: "female" },
  { name: "守護者熾天使羽毛",         type: "A", chance: 1.04, gender: null },
  { name: "崇高熾天使",               type: "A", chance: 1.08, gender: null },
  { name: "高雅熾天使",               type: "A", chance: 1.08, gender: null },
  { name: "戰鬥熾天使",               type: "A", chance: 0.97, gender: null },
  { name: "可愛兔兔殺人鯨動畫名牌戒指", type: "A", chance: 0.83, gender: null },
  { name: "可愛兔兔殺人鯨動畫聊天戒指", type: "A", chance: 0.83, gender: null },

  // 🔹 B（仲夏夜）
  { name: "仲夏夜記憶",       type: "B", chance: 1.69, gender: null },
  { name: "仲夏夜回憶",       type: "B", chance: 2.24, gender: null },
  { name: "仲夏夜精靈(男)",   type: "B", chance: 1.64, gender: "male" },
  { name: "仲夏夜妖精(女)",   type: "B", chance: 1.64, gender: "female" },
  { name: "仲夏夜訊息",       type: "B", chance: 1.69, gender: null },
  { name: "仲夏夜蝴蝶",       type: "B", chance: 1.69, gender: null },
  { name: "仲夏夜花籃",       type: "B", chance: 1.59, gender: null },
  { name: "光輝的鯊魚之槍",   type: "B", chance: 1.59, gender: null },
  { name: "臨危不亂鞋子",     type: "B", chance: 1.69, gender: null },

  // 🔹 A（指揮家/音樂會）
  { name: "寂靜的緊張感",         type: "A", chance: 1.05, gender: null },
  { name: "獨奏的華麗",           type: "A", chance: 1.05, gender: null },
  { name: "苦惱的指揮家",         type: "A", chance: 1.03, gender: null },
  { name: "優雅的指揮家",         type: "A", chance: 1.03, gender: null },
  { name: "孤獨的旋律",           type: "A", chance: 1.09, gender: null },
  { name: "單獨舞台的旋律",       type: "A", chance: 1.09, gender: null },
  { name: "藝術家的理想",         type: "A", chance: 1.03, gender: null },
  { name: "寂靜中的音樂會",       type: "A", chance: 0.97, gender: null },
  { name: "優美的演奏",           type: "A", chance: 0.97, gender: null },

  // 🔹 B（草莓牛奶）
  { name: "草莓牛奶的角",       type: "B", chance: 1.68, gender: null },
  { name: "草莓牛奶套服(男)",   type: "B", chance: 1.63, gender: "male" },
  { name: "草莓牛奶套服(女)",   type: "B", chance: 1.63, gender: "female" },
  { name: "草莓牛奶鞋",         type: "B", chance: 1.64, gender: null },
  { name: "草莓牛奶",           type: "B", chance: 1.63, gender: null },
  { name: "草莓牛奶棒",         type: "B", chance: 1.59, gender: null },
  { name: "草莓牛奶瓶聊天戒指", type: "B", chance: 1.69, gender: null },
  { name: "草莓牛奶瓶名牌戒指", type: "B", chance: 1.69, gender: null },
];
