const potentialList = [
  { name: "STR", value: "25", chance: 0.83 },
  { name: "DEX", value: "25", chance: 0.83 },
  { name: "INT", value: "25", chance: 0.83 },
  { name: "LUK", value: "25", chance: 0.83 },
  { name: "MaxHP", value: "500", chance: 0.56 },
  { name: "MaxMP", value: "500", chance: 0.56 },
  { name: "DEX", value: "1", chance: 1.11 },
  { name: "移動速度", value: "10", chance: 0.56 },
  { name: "跳躍力", value: "10", chance: 0.56 },
  { name: "物理攻擊力", value: "25", chance: 1.11 },
  { name: "魔法攻擊力", value: "25", chance: 1.11 },
  { name: "防禦力", value: "25", chance: 3.61 },
  { name: "爆擊率", value: "25", chance: 3.06 },
  { name: "最終傷害", value: "25", chance: 3.06 },
  { name: "全屬性", value: "25", chance: 3.06 },
  { name: "一定秒數內恢復HP", value: "20", chance: 1.94 },
  { name: "一定秒數內恢復MP", value: "20", chance: 1.94 },
  { name: "STR%", value: "20", chance: 5.0 },
  { name: "DEX%", value: "20", chance: 5.0 },
  { name: "INT%", value: "20", chance: 5.0 },
  { name: "LUK%", value: "20", chance: 5.0 },
  { name: "MaxHP%", value: "20", chance: 4.17 },
  { name: "MaxMP%", value: "20", chance: 4.17 },
  { name: "DEX%", value: "1", chance: 2.78 },
  { name: "物理攻擊力%", value: "20", chance: 4.17 },
  { name: "魔法攻擊力%", value: "20", chance: 4.17 },
  { name: "防禦力%", value: "14", chance: 2.78 },
  { name: "攻擊時一定機率恢復HP", value: "3 / 50", chance: 2.78 },
  { name: "攻擊時一定機率恢復MP", value: "3 / 50", chance: 2.78 },
  { name: "攻擊時一定機率對單一怪造成中毒效果", value: "12 / 3", chance: 2.22 },
  { name: "攻擊時一定機率對單一怪造成昏迷效果", value: "12 / 3", chance: 2.22 },
  { name: "攻擊時一定機率對單一怪造成黑暗效果", value: "12 / 3", chance: 2.22 },
  { name: "攻擊時一定機率對單一怪造成緩速效果", value: "12 / 3", chance: 2.22 },
  { name: "攻擊時一定機率對單一怪造成冰凍效果", value: "12 / 3", chance: 2.22 },
  { name: "攻擊時一定機率對單一怪造成封印效果", value: "12 / 3", chance: 2.22 },
  { name: "無視防禦力", value: "50", chance: 2.78 },
  { name: "依照角色一定的攻擊力來追加萌獸攻擊力", value: "90", chance: 2.78 },
  { name: "依照角色一定的屬性來追加萌獸攻擊力", value: "90", chance: 4.17 },
  { name: "加持技能持續時間", value: "55", chance: 2.78 },
  { name: "增加被動技能等級", value: "2", chance: 2.78 },
];