// units.js
export const units = [
  // === A 級角色 ===
  { id: "a001", name: "[北風使者]夏洛特•斯可波夫斯加", rarity: "A", img: "CSkopovskayaDefault_R1.png" },
  { id: "a002", name: "[真紅的修女]瑪麗亞•黛•安傑利斯", rarity: "A", img: "MdAngelisDefault_R1.png" },
  { id: "a003", name: "[華麗的飛天女神]芙里提卡•巴拉克里希南", rarity: "A", img: "VBalakrishnanDefault_R1.png" },
  { id: "a004", name: "[難解事件的探求者]艾琳•雷德梅因", rarity: "A", img: "IRedmayneDefault_R1.png" },
  { id: "a005", name: "[臥龍的代言人]李 映夏", rarity: "A", img: "LShanhuaDefault_R1.png" },
  { id: "a006", name: "[星之繼承者]卡羅爾•利帕", rarity: "A", img: "CReaperDefault_R1.png" },
  { id: "a007", name: "[Highway of Angels]黑澤 真希", rarity: "A", img: "MKurosawaDefault_R1.png" },
  { id: "a008", name: "[天誅斬影]夏目 祈", rarity: "A", img: "CSkopovskayaDefault_R1.png" },
  { id: "a009", name: "[天才砲灰]松岡 綺羅路", rarity: "A", img: "CMatsuokaDefault_R1.png" },
  { id: "a010", name: "[危險戀愛指揮家]華村 詩記", rarity: "A", img: "SHanamuraDefault_R1.png" },
  { id: "a011", name: "[小巧高尚]丸山 奏多", rarity: "A", img: "KMaruyamaDefault_R1.png" },
  { id: "a012", name: "[皇室級管家]柳 美音", rarity: "A", img: "MYanagiDefault_R1.png" },
  { id: "a013", name: "[六宇亞的陶醉]大島 六宇亞", rarity: "A", img: "MuOhshimaDefault_R1.png" },
  { id: "a014", name: "[五十鈴的秘密]大島 五十鈴", rarity: "A", img: "IrOhshimaDefault_R1.png" },
  { id: "a015", name: "[四葉草的倦怠]大島 四葉草", rarity: "A", img: "YoOhshimaDefault_R1.png" },
  { id: "a016", name: "[三野里的疾馳]大島 三野里", rarity: "A", img: "MiOhshimaDefault_R1.png" },
  { id: "a017", name: "[二以奈的氣質]大島 二以奈", rarity: "A", img: "NiOhshimaDefault_R1.png" },
  { id: "a018", name: "[一千子的擁抱]大島 一千子", rarity: "A", img: "IcOhshimaDefault_R1.png" },
  { id: "a019", name: "[深海的學習者]瑞原 藍娜", rarity: "A", img: "AMizuharaDefault_R1.png" },
  { id: "a020", name: "[悲觀王牌]伊達 朱里", rarity: "A", img: "ADateDefault_R1.png" },
  { id: "a021", name: "[母愛的接球手]室伏 理沙", rarity: "A", img: "RMurohushiDefault_R1.png" },
  { id: "a022", name: "[Metal Carazy]命 吹雪", rarity: "A", img: "FMikotoDefault_R1.png" },
  { id: "a023", name: "[輕鬆多彩]石井 色葉", rarity: "A", img: "IIshiiDefault_R1.png" },
  { id: "a024", name: "[最年少名人]二階堂三鄉", rarity: "A", img: "MNikaidoDefault_R1.png" },
  { id: "a025", name: "[氣派佳人]藏 里見", rarity: "A", img: "SKuraDefault_R1.png" },
  { id: "a026", name: "[輕搖的火焰]小笠原 緋雨", rarity: "A", img: "HOgasawaraDefault_R1.png" },
  { id: "a027", name: "[朵洛雷斯的魅惑]管原 千惠", rarity: "A", img: "CSugaharaDefault_R1.png" },
  { id: "a028", name: "[幽雅深邃 惹人憐愛]桐生 美也", rarity: "A", img: "MKiryuDefault_R1.png" },
  { id: "a029", name: "[禪定 有備無患]月城 最中", rarity: "A", img: "MTsukishiroDefault_R1.png" },
  { id: "a030", name: "[Ally]白河 結奈", rarity: "A", img: "YShirakawaDefault_R1.png" },
  { id: "a031", name: "[生意和微笑]佐月 麻里", rarity: "A", img: "MSatsukiDefault_R1.png" },
  { id: "a032", name: "[碧落的忍者]神崎 阿黛爾海德", rarity: "A", img: "AKanzakiDefault_R1.png" },
  { id: "a033", name: "[蟹手使魔]豐後 彌生", rarity: "A", img: "YBungoDefault_R1.png" },
  { id: "a034", name: "[渴望悠久的魔術師]天音 巫呼", rarity: "A", img: "MTenneDefault_R1.png" },
  { id: "a035", name: "[水晶的指引]櫻庭 星羅", rarity: "A", img: "SSakurabaDefault_R1.png" },
  { id: "a036", name: "[走自己的路]山脇•波昂•伊瓦爾", rarity: "A", img: "BIYamawakiDefault_R1.png" },
  { id: "a037", name: "[戰場的咆嘯]白虎", rarity: "A", img: "ByakkoDefault_R1.png" },
  { id: "a038", name: "[戰場的聳動]柊木 梢", rarity: "A", img: "KHiiragiDefault_R1.png" },
  { id: "a039", name: "[戰場的科學家]樋口 聖華", rarity: "A", img: "SHiguchiDefault_R1.png" },
  { id: "a040", name: "[戰場的火苗]水瀨 李", rarity: "A", img: "SMinaseDefault_R1.png" },
  { id: "a041", name: "[戰場的煙火]水瀨 莓", rarity: "A", img: "IMinaseDefault_R1.png" },
  { id: "a042", name: "[戰場的落英]蒼井 繪梨花", rarity: "A", img: "EAoiDefault_R1.png" },
  { id: "a043", name: "[Truth or Lies]國見 玉", rarity: "A", img: "TKunimiDefault_R1.png" },
  { id: "a044", name: "[Laugh or Cry]朝倉 可憐", rarity: "A", img: "KarenDefault_R1.png" },
  { id: "a045", name: "[Serious or Stupid]東城 司", rarity: "A", img: "TTojoDefault_R1.png" },
  { id: "a046", name: "[Plain or Wild]逢川 惠", rarity: "A", img: "MAikawaDefault_R1.png" },
  { id: "a047", name: "[Attack or March]和泉 由希", rarity: "A", img: "YIzumiDefault_R1.png" },
  { id: "a048", name: "[Attack or Misuc]茅森 月歌", rarity: "A", img: "RKayamoriDefault_R1.png" },
  // === S 級角色 ===
  { id: "s001", name: "[和煦的眼神]夏洛特•斯可波夫斯加", rarity: "S", img: "CSkopovskayaDefault_R2a.png" },
  { id: "s002", name: "[雪花的鄉愁]夏洛特•斯可波夫斯加", rarity: "S", img: "CSkopovskayaDefault_R2.png" },
  { id: "s004", name: "[萊姆與草莓]瑪麗亞•黛•安傑利斯", rarity: "S", img: "MdAngelisDefault_R2a.png" },
  { id: "s005", name: "[華麗的日常]芙里提卡•巴拉克里希南", rarity: "S", img: "VBalakrishnanDefault_R2a.png" },
  { id: "s006", name: "[貝克街的軌跡]艾琳•雷德梅因", rarity: "S", img: "IRedmayneDefault_R2.png" },
  { id: "s007", name: "[武成在天]李 映夏", rarity: "S", img: "LShanhuaDefault_R2.png" },
  { id: "s008", name: "[心之風景]卡羅爾•利帕", rarity: "S", img: "CReaperDefault_R2.png" },
  { id: "s009", name: "[總長喜歡讀書]黑澤 真希", rarity: "S", img: "MKurosawaDefault_R2a.png" },
  { id: "s010", name: "[彼岸的劊子手]夏目 祈", rarity: "S", img: "INatsumeDefault_R2.png" },
  { id: "s011", name: "[林間隙光的奏鳴曲]華村 詩記", rarity: "S", img: "SHanamuraDefault_R2.png" },
  { id: "s012", name: "[將死是敗北的滋味]丸山 奏多", rarity: "S", img: "KMaruyamaDefault_R2b.png" },
  { id: "s013", name: "[林間隙光的庭院]丸山 奏多", rarity: "S", img: "KMaruyamaDefault_R2a.png" },
  { id: "s014", name: "[滅私奉公的誠信]柳 美音", rarity: "S", img: "MYanagiDefault_R2.png" },
  { id: "s015", name: "[狂喜奔馳]大島 六宇亞", rarity: "S", img: "MuOhshimaDefault_R2.png" },
  { id: "s016", name: "[平穩的風情]大島 五十鈴", rarity: "S", img: "IrOhshimaDefault_R2.png" },
  { id: "s017", name: "[我的搭檔]大島 三野里", rarity: "S", img: "MiOhshimaDefault_R2a.png" },
  { id: "s018", name: "[飛毛腿送貨員]大島 三野里", rarity: "S", img: "MiOhshimaDefault_R2.png" },
  { id: "s019", name: "[戰線伸展台]大島 二以奈", rarity: "S", img: "NiOhshimaDefault_R2.png" },
  { id: "s020", name: "[同床異夢消解時]大島 一千子", rarity: "S", img: "IcOhshimaDefault_R2.png" },
  { id: "s021", name: "[來自深淵的邀請]瑞原 藍娜", rarity: "S", img: "AMizuharaDefault_R2.png" },
  { id: "s022", name: "[蔚藍織花]室伏 理沙", rarity: "S", img: "RMurohushiDefault_R2a.png" },
  { id: "s023", name: "[痛痛飛走~]室伏 理沙", rarity: "S", img: "RMurohushiDefault_R2.png" },
  { id: "s024", name: "[純粹情感]石井 色葉", rarity: "S", img: "IIshiiDefault_R2a.png" },
  { id: "s025", name: "[色彩繽紛的靈感]石井 色葉", rarity: "S", img: "IIshiiDefault_R2.png" },
  { id: "s026", name: "[甜蜜的優閒時光]二階堂三鄉", rarity: "S", img: "MNikaidoDefault_R2a.png" },
  { id: "s027", name: "[今昔之感 思緒萬千]二階堂三鄉", rarity: "S", img: "MNikaidoDefault_R2.png" },
  { id: "s028", name: "[身處清流]藏 里見", rarity: "S", img: "SKuraDefault_R2.png" },
  { id: "s029", name: "[靜寂閑雅的休息時間]小笠原 緋雨", rarity: "S", img: "HOgasawaraDefault_R2.png" },
  { id: "s030", name: "[一掃反覆無常的陰霾]管原 千惠", rarity: "S", img: "CSugaharaDefault_R2.png" },
  { id: "s031", name: "[神祠拜望 夢如似幻]桐生 美也", rarity: "S", img: "MKiryuDefault_R2.png" },
  { id: "s032", name: "[只要有妳在]白河 結奈", rarity: "S", img: "YShirakawaDefault_R2a.png" },
  { id: "s033", name: "[Sign]白河 結奈", rarity: "S", img: "YShirakawaDefault_R2.png" },
  { id: "s034", name: "[掌心上的美好]豐後 彌生", rarity: "S", img: "YBungoDefault_R2.png" },
  { id: "s035", name: "[望紅危渡夢浮橋]天音 巫呼", rarity: "S", img: "MTenneDefault_R2.png" },
  { id: "s036", name: "[雨過天晴 心曠神怡]櫻庭 星羅", rarity: "S", img: "SSakurabaDefault_R2.png" },
  { id: "s037", name: "[魔王歸來]山脇•波昂•伊瓦爾", rarity: "S", img: "BIYamawakiDefault_R2.png" },
  { id: "s038", name: "[海邊的瞌睡]白虎", rarity: "S", img: "ByakkoSwim2025_R2.png" },
  { id: "s039", name: "[某位少女的故事]樋口 聖華", rarity: "S", img: "SHiguchiDefault_R2.png" },
  { id: "s040", name: "[物以類聚]水瀨 李", rarity: "S", img: "SMinaseDefault_R2a.png" },
  { id: "s041", name: "[積雨雲]水瀨 李", rarity: "S", img: "SMinaseDefault_R2.png" },
  { id: "s042", name: "[剎那回憶]蒼井 繪梨花", rarity: "S", img: "EAoiDefault_R2.png" },
  { id: "s043", name: "[天真無邪的願望]國見 玉", rarity: "S", img: "TKunimiDefault_R2a.png" },
  { id: "s044", name: "[心動不己的弧光]國見 玉", rarity: "S", img: "TKunimiDefault_R2.png" },
  { id: "s045", name: "[狂悖暴戾的隨機漫步]朝倉 可憐", rarity: "S", img: "KarenDefault_R2a.png" },
  { id: "s046", name: "[最前線的堡壘]朝倉 可憐", rarity: "S", img: "KarenDefault_R2.png" },
  { id: "s047", name: "[嗟嘆的沉睡者]東城 司", rarity: "S", img: "TTojoDefault_R2.png" },
  { id: "s048", name: "[Impact Stream]逢川 惠", rarity: "S", img: "MAikawaDefault_R2.png" },
  { id: "s049", name: "[夢幻的Sleeping Ocelot]和泉 由希", rarity: "S", img: "YIzumiDefault_R2.png" },
  { id: "s050", name: "[戰場的品味]茅森 月歌", rarity: "S", img: "RKayamoriDefault_R2.png" },

  // === SS 級角色 ===
  //{ id: "ss999", name: "[激烈!招來勝利的一球入魂!]茅森 月歌", rarity: "SS", img: "RKayamoriHR_R3.png" }, // PU
  //{ id: "ss999", name: "[激戰!轟出去的全壘打]水瀨 莓", rarity: "SS", img: "IMinaseHR_R3.png" },
  
  { id: "ss114", name: "[黎明的激昂靈魂]茅森 月歌", rarity: "SS", img: "RKayamoriDefault_R3.png" },
  { id: "ss001", name: "[騎士的真洪殘響]茅森 月歌", rarity: "SS", img: "RKayamoriGothic_R3.png" },
  { id: "ss002", name: "[夜間巡航護送者]茅森 月歌", rarity: "SS", img: "RKayamoriAnniv2023_R3.png" },
  { id: "ss003", name: "[皎潔之華麗歌姬]茅森 月歌", rarity: "SS", img: "RKayamoriDiva_R3.png" },
  { id: "ss115", name: "[終焉Spitfire]和泉 由希", rarity: "SS", img: "YIzumiDefault_R3.png" },
  { id: "ss004", name: "[夏樁 光彩奪目的夜光星]和泉 由希", rarity: "SS", img: "YIzumiYukata2022_R3.png" },
  { id: "ss005", name: "[夜間巡航服務員]和泉 由希", rarity: "SS", img: "YIzumiAnniv2023_R3.png" },
  { id: "ss006", name: "[舞出新的自我]和泉 由希", rarity: "SS", img: "YIzumiBeauty_R3.png" },
  { id: "ss007", name: "[盼望的紅玉]和泉 由希", rarity: "SS", img: "YIzumiSnowWhite_R3.png" },
  { id: "ss116", name: "[Ikki Burst Strike]逢川 惠", rarity: "SS", img: "MAikawaPrecious_R3.png" },
  { id: "ss008", name: "[一夜之夢]逢川 惠", rarity: "SS", img: "MAikawaPrecious_R3.png" },
  { id: "ss009", name: "[歡欣雀躍Fuel]逢川 惠", rarity: "SS", img: "MAikawaMaiden_R3.png" },
  { id: "ss010", name: "[薄暮時分進益者]逢川 惠", rarity: "SS", img: "MAikawaSuite_R3_Low.png" },
  { id: "ss011", name: "[永無止盡的夏日]逢川 惠", rarity: "SS", img: "MAikawaSwim2024_R3.png" },
  { id: "ss117", name: "[與死共舞的美少女]東城 司", rarity: "SS", img: "TTojoDefault_R3.png" },
  { id: "ss012", name: "[盛夏的Prayer]東城 司", rarity: "SS", img: "TTojoSwim2022_R3_Low.png" },
  { id: "ss013", name: "[特務機關無聲者]東城 司", rarity: "SS", img: "TTojoSuite_R3_Low.png" },
  { id: "ss014", name: "[惡兔亂鬥]東城 司", rarity: "SS", img: "TTojoRabbit_R3.png" },
  { id: "ss015", name: "[悲心的輓歌]東城 司", rarity: "SS", img: "TTojoMourning_R3.png" },
  { id: "ss118", name: "[紅蓮月華Kikkrazor]朝倉 可憐", rarity: "SS", img: "KarenDefault_R3.png" },
  { id: "ss016", name: "[特務機關搗毀者]朝倉 可憐", rarity: "SS", img: "KarenSuite_R3.png" },
  { id: "ss017", name: "[盛夏的鯊人魔]朝倉 可憐", rarity: "SS", img: "KarenSwim2024_R3.png" },
  { id: "ss119", name: "[天使艦長的氣勢一閃]國見 玉", rarity: "SS", img: "TKunimiDefault_R3.png" },
  { id: "ss018", name: "[魔法王國的元素精靈]國見 玉", rarity: "SS", img: "TKunimiMagical_R3.png" },
  { id: "ss019", name: "[衝撞!!空氣貝斯]國見 玉", rarity: "SS", img: "TKunimiNewYear2023_R3.png" },
  { id: "ss020", name: "[夢幻的珊瑚紅]國見 玉", rarity: "SS", img: "TKunimiSwim2023_R3.png" },
  { id: "ss021", name: "[薄暮時分尋億者]國見 玉", rarity: "SS", img: "TKunimiSuite_R3.png" },
  { id: "ss120", name: "[鼓舞人心]蒼井 繪梨花", rarity: "SS", img: "EAoiDefault_R3.png" },
  { id: "ss022", name: "[傳遞奇蹟]蒼井 繪梨花", rarity: "SS", img: "EAoiWaitress_R3.png" },
  { id: "ss023", name: "[閃亮亮究級偶像]蒼井 繪梨花", rarity: "SS", img: "EAoiNewYear2024_R3.png" },
  { id: "ss024", name: "[響亮戰嗥]蒼井 繪梨花", rarity: "SS", img: "EAoiMilitary_R3.png" },
  { id: "ss121", name: "[欣喜若狂墜入愛河]水瀨 莓", rarity: "SS", img: "IMinaseDefault_R3.png" },
  { id: "ss025", name: "[萌殺你的眼]水瀨 莓", rarity: "SS", img: "IMinaseNewYear2024_R3.png" },
  { id: "ss026", name: "[冷豔的沉默殺手]水瀨 莓", rarity: "SS", img: "IMinaseAssassin_R3.png" },
  { id: "ss122", name: "[殘光]水瀨 李", rarity: "SS", img: "SMinaseDefault_R3.png" },
  { id: "ss027", name: "[熱氣薰騰暗殺者]水瀨 李", rarity: "SS", img: "SMinaseSwim2022_R3.png" },
  { id: "ss028", name: "[愛憐的微笑]水瀨 李", rarity: "SS", img: "SMinaseDoll_R3.png" },
  { id: "ss123", name: "[生者的恆定性]樋口 聖華", rarity: "SS", img: "SHiguchiDefault_R3.png" },
  { id: "ss029", name: "[宇宙探究星光璀璨]樋口 聖華", rarity: "SS", img: "SHiguchiGrace_R3.png" },
  { id: "ss030", name: "[黎明的淨化作用]樋口 聖華", rarity: "SS", img: "SHiguchiDoctor_R3.png" },
  { id: "ss031", name: "[夕陽下的烏托邦]樋口 聖華", rarity: "SS", img: "SHiguchiSwim2025_R3.png" },
  { id: "ss124", name: "[蒼蘭夜曲]柊木 梢", rarity: "SS", img: "KHiiragiDefault_R3.png" },
  { id: "ss032", name: "[終劇的黃昏]柊木 梢", rarity: "SS", img: "KHiiragiBloody_R3.png" },
  { id: "ss033", name: "[跳躍踏步滑倒]柊木 梢", rarity: "SS", img: "KHiiragiWaitress_R3.png" },
  { id: "ss034", name: "[泳池畔的瞬間]柊木 梢", rarity: "SS", img: "KHiiragiSwim2025_R3.png" },
  { id: "ss125", name: "[狂怒野獸]白虎", rarity: "SS", img: "ByakkoDefault_R3.png" },
  { id: "ss035", name: "[將之善和]白虎", rarity: "SS", img: "ByakkoBeast_R3.png" },
  { id: "ss126", name: "[Enon Knight]山脇•波昂•伊瓦爾", rarity: "SS", img: "BIYamawakiDefault_R3.png" },
  { id: "ss036", name: "[Holy knight]山脇•波昂•伊瓦爾", rarity: "SS", img: "BIYamawakiXmas2022_R3.png" },
  { id: "ss037", name: "[Daydream Believer]山脇•波昂•伊瓦爾", rarity: "SS", img: "BIYamawakiDaydream_R3.png" },
  { id: "ss038", name: "[撥雲見日]山脇•波昂•伊瓦爾", rarity: "SS", img: "BIYamawakiWhiteSuit_R3.png" },
  { id: "ss127", name: "[在星海浮沉的占星師]櫻庭 星羅", rarity: "SS", img: "SSakurabaDefault_R3.png" },
  { id: "ss039", name: "[對決 空氣舞台]櫻庭 星羅", rarity: "SS", img: "SSakurabaNewYear2023_R3.png" },
  { id: "ss040", name: "[Sanctuart Veil]櫻庭 星羅", rarity: "SS", img: "SSakurabaBride_R3.png" },
  { id: "ss041", name: "[侍奉魔王的幻影大魔島士]櫻庭 星羅", rarity: "SS", img: "SSakurabaEvil_R3.png" },
  { id: "ss128", name: "[神祕莫測的妳]天音 巫呼", rarity: "SS", img: "MTenneDefault_R3.png" },
  { id: "ss042", name: "[山脇大人的手下:魔法喵喵]天音 巫呼", rarity: "SS", img: "MTenneAnimal_R3.png" },
  { id: "ss043", name: "[最美妙的片刻]天音 巫呼", rarity: "SS", img: "MTenneWizard_R3.png" },
  { id: "ss044", name: "[侍奉魔王的冥界死靈法師]天音 巫呼", rarity: "SS", img: "MTenneEvil_R3.png" },
  { id: "ss129", name: "[夜空中的sShining Star]豐後 彌生", rarity: "SS", img: "YBungoDefault_R3.png" },
  { id: "ss045", name: "[Happy Legion]豐後 彌生", rarity: "SS", img: "YBungoXmas2022_R3.png" },
  { id: "ss046", name: "[賞花怪人糰子串]豐後 彌生", rarity: "SS", img: "YBungoDango_R3.png" },
  { id: "ss130", name: "[東拼西湊的忍法大亂鬥]神崎 阿黛爾海德", rarity: "SS", img: "AKanzakiDefault_R3.png" },
  { id: "ss047", name: "[雪花的Hexerei]神崎 阿黛爾海德", rarity: "SS", img: "AKanzakiAgent_R3.png" },
  { id: "ss048", name: "[少女的休息時間]神崎 阿黛爾海德", rarity: "SS", img: "AKanzakiSwim2024_R3.png" },
  { id: "ss049", name: "[向日葵]神崎 阿黛爾海德", rarity: "SS", img: "AKanzakiDirndl_R3.png" },
  { id: "ss131", name: "[甜美的Muzzle]佐月 麻里", rarity: "SS", img: "MSatsukiDefault_R3.png" },
  { id: "ss132", name: "[暗殺者忍法絡繹不絕]佐月 麻里", rarity: "SS", img: "MSatsukiAgent_R3.png" },//要補上全部
  { id: "ss050", name: "[Crying Tears]佐月 麻里", rarity: "SS", img: "MSatsukiBride_R3.png" },
  { id: "ss051", name: "[高如豔陽]佐月 麻里", rarity: "SS", img: "MSatsukiSwim2024_R3.png" },
  { id: "ss052", name: "[侍奉魔王的混世謀臣]佐月 麻里", rarity: "SS", img: "MSatsukiEvil_R3.png" },
  { id: "ss133", name: "[Awakening lris]白河 結奈", rarity: "SS", img: "YShirakawaDefault_R3.png" },
  { id: "ss053", name: "[Infernal Sanctuart]白河 結奈", rarity: "SS", img: "YShirakawaBloom_R3.png" },
  { id: "ss054", name: "[盛夏的前衛峰憲兵]白河 結奈", rarity: "SS", img: "YShirakawaSwim2023_R3.png" },
  { id: "ss055", name: "[黃昏綻放的角宿一]白河 結奈", rarity: "SS", img: "YShirakawaWhiteSuit_R3.png" },
  { id: "ss134", name: "[揮別迷惘 一閃心靜]月城 最中", rarity: "SS", img: "MTsukishiroDefault_R3.png" },
  { id: "ss056", name: "[不為人知的空暇]月城 最中", rarity: "SS", img: "MTsukishiroRugged_R3.png" },
  { id: "ss057", name: "[思念春吹雪]月城 最中", rarity: "SS", img: "MTsukishiroWarrior_R3.png" },
  { id: "ss135", name: "[星密如林 箭雨留人]桐生 美也", rarity: "SS", img: "MKiryuDefault_R3 .png" },
  { id: "ss058", name: "[豐樂之神秘]桐生 美也", rarity: "SS", img: "MKiryuGothic_R3.png" },
  { id: "ss059", name: "[轉瞬 一夜夢火]桐生 美也", rarity: "SS", img: "MKiryuCerulean_R3.png" },
  { id: "ss060", name: "[海風的導引]桐生 美也", rarity: "SS", img: "MKiryuSwim2025_R3.png" },
  { id: "ss136", name: "[最後的蘿莉塔白皮書]管原 千惠", rarity: "SS", img: "CSugaharaDefault_R3.png" },
  { id: "ss061", name: "[亡國的純真心靈]管原 千惠", rarity: "SS", img: "CSugaharaPurity_R3.png" },
  { id: "ss062", name: "[堅忍克己的蘿莉塔]管原 千惠", rarity: "SS", img: "CSugaharaExcellency_R3.png" },
  { id: "ss063", name: "[野性狂騷]管原 千惠", rarity: "SS", img: "CSugaharaBeast_R3.png" },
  { id: "ss137", name: "[矇矓月夜的子彈]小笠原 緋雨", rarity: "SS", img: "HOgasawaraDefault_R3.png" },
  { id: "ss064", name: "[天才劍士萌起來]小笠原 緋雨", rarity: "SS", img: "HOgasawaraCutieMaid_R3.png" },
  { id: "ss065", name: "[希求與渴仰]小笠原 緋雨", rarity: "SS", img: "HOgasawaraNightdress_R3.png" },
  { id: "ss066", name: "[夏暮石榴石]小笠原 緋雨", rarity: "SS", img: "HOgasawaraHighSchoolLife_R3.png" },
  { id: "ss138", name: "[豐收之神降臨於此]藏 里見", rarity: "SS", img: "SKuraDefault_R3.png" },
  { id: "ss067", name: "[年輕老闆娘的每一天]藏 里見", rarity: "SS", img: "SKuraLandlady_R3.png" },
  { id: "ss068", name: "[暑氣蒸騰的精采對決]藏 里見", rarity: "SS", img: "SKuraSwim2025_R3.png" },
  { id: "ss139", name: "[至高無上的終局]二階堂三鄉", rarity: "SS", img: "MNikaidoDefault_R3.png" },
  { id: "ss069", name: "[Holiday Ring a Bell]二階堂三鄉", rarity: "SS", img: "MNikaidoXmas2023_R3.png" },
  { id: "ss070", name: "[Lead by Example]二階堂三鄉", rarity: "SS", img: "MNikaidoWhiteSuit_R3.png" },
  { id: "ss140", name: "[破壞無色彩之牆]石井 色葉", rarity: "SS", img: "IIshiiDefault_R3.png" },
  { id: "ss071", name: "[滿溢的情感]石井 色葉", rarity: "SS", img: "IIshiiCasual_R3.png" },
  { id: "ss072", name: "[幸福彩度]石井 色葉", rarity: "SS", img: "IIshiiBride_R3.png" },
  { id: "ss141", name: "[末日要幹嘛?]命 吹雪", rarity: "SS", img: "FMikotoDefault_R3.png" },
  { id: "ss073", name: "[Frizen Moon Melting Heart]命 吹雪", rarity: "SS", img: "FMikotoXmas2024_R3.png" },
  { id: "ss142", name: "[趕快回家吧]室伏 理沙", rarity: "SS", img: "RMurohushiDefault_R3.png" },
  { id: "ss074", name: "[潛入 面帶笑容參加技術交流會]室伏 理沙", rarity: "SS", img: "RMurohushiRace_R3.png" },
  { id: "ss075", name: "[今晚 在櫻花照映之下]室伏 理沙", rarity: "SS", img: "RMurohushiMaiden_R3.png" },
  { id: "ss143", name: "[網球場的惡魔]伊達 朱里", rarity: "SS", img: "ADateDefault_R3.png" },
  { id: "ss076", name: "[Holiday Star Night]伊達 朱里", rarity: "SS", img: "ADateXmas2023_R3.png" },
  { id: "ss077", name: "[幸運冬麗]伊達 朱里", rarity: "SS", img: "ADateFurisode2025_R3.png" },
  { id: "ss144", name: "[禁錮虎鯨]瑞原 藍娜", rarity: "SS", img: "AMizuharaDefault_R3.png" },
  { id: "ss078", name: "[衝鋒!擊刺!鮪魚!]瑞原 藍娜", rarity: "SS", img: "AMizuharaPirates_R3.png" },
  { id: "ss079", name: "[獻給大海的愛情]瑞原 藍娜", rarity: "SS", img: "AMizuharaJellyfish_R3.png" },
  { id: "ss080", name: "[跳進閃閃發亮的夏天]瑞原 藍娜", rarity: "SS", img: "AMizuharaSwim2025_R3.png" },
  { id: "ss145", name: "[無窮慈愛的守護者]大島 一千子", rarity: "SS", img: "IcOhshimaDefault_R3.png" },
  { id: "ss081", name: "[Sweet Phantasy]大島 一千子", rarity: "SS", img: "IcOhshimaBride_R3.png" },
  { id: "ss082", name: "[指引的光輝]大島 一千子", rarity: "SS", img: "IcOhshimaWhiteSuit_R3.png" },
  { id: "ss146", name: "[Brand New Mind]大島 二以奈", rarity: "SS", img: "NiOhshimaDefault_R3.png" },
  { id: "ss083", name: "[心緒昂揚溫泉鄉]大島 二以奈", rarity: "SS", img: "NiOhshimaYukata2023_R3.png" },
  { id: "ss084", name: "[海濱的純真回憶]大島 二以奈", rarity: "SS", img: "NiOhshimaPrivate_R3.png" },
  { id: "ss147", name: "[REALIZE Your Mind]大島 三野里", rarity: "SS", img: "MiOhshimaDefault_R3.png" },
  { id: "ss085", name: "[絢麗華美的花樣少女]大島 三野里", rarity: "SS", img: "MiOhshimaYukata2024_R3.png" },
  { id: "ss148", name: "[慵懶破滅]大島 四葉草", rarity: "SS", img: "YoOhshimaDefault_R3.png" },
  { id: "ss086", name: "[傭懶睡衣之夜]大島 四葉草", rarity: "SS", img: "YoOhshimaSheep_R3.png" },
  { id: "ss087", name: "[裊裊溫泉樂]大島 四葉草", rarity: "SS", img: "YoOhshimaYukata2025_R3.png" },
  { id: "ss149", name: "[通往勝利的鑰匙]大島 五十鈴", rarity: "SS", img: "IrOhshimaDefault_R3.png" },
  { id: "ss088", name: "[出浴夢想鄉]大島 五十鈴", rarity: "SS", img: "IrOhshimaYukata2023_R3.png" },
  { id: "ss089", name: "[Magic of smile]大島 五十鈴", rarity: "SS", img: "IrOhshimaShowTime_R3.png" },
  { id: "ss150", name: "[危機太讚了]大島 六宇亞", rarity: "SS", img: "MuOhshimaDefault_R3.png" },
  { id: "ss090", name: "[初春迎風]大島 六宇亞", rarity: "SS", img: "MuOhshimaFurisode2024_R3_Low.png" },
  { id: "ss091", name: "[漣漪好心情]大島 六宇亞", rarity: "SS", img: "MuOhshimaPrivate_R3.png" },
  { id: "ss151", name: "[Wild Rose]柳 美音", rarity: "SS", img: "MYanagiDefault_R3.png" },
  { id: "ss092", name: "[夜風中的Chill Time]柳 美音", rarity: "SS", img: "MYanagiPunk_R3.png" },
  { id: "ss093", name: "[夜晚的香氣 薔薇的音調]柳 美音", rarity: "SS", img: "MYanagiWhiteSuit_R3.png" },
  { id: "ss152", name: "[持續進化的感知能力]丸山 奏多", rarity: "SS", img: "KMaruyamaDefault_R3.png" },
  { id: "ss094", name: "[微笑綻放]丸山 奏多", rarity: "SS", img: "KMaruyamaPanda_R3.png" },
  { id: "ss153", name: "[妳的Unisono]華村 詩記", rarity: "SS", img: "SHanamuraDefault_R3.png" },
  { id: "ss095", name: "[在耀的CANTANILE]華村 詩記", rarity: "SS", img: "SHanamuraConductor_R3.png" },
  { id: "ss154", name: "[追風逐電 滅亡的狼煙]松岡 綺羅路", rarity: "SS", img: "CMatsuokaDefault_R3.png" },
  { id: "ss096", name: "[祕密的咖啡小憩]松岡 綺羅路", rarity: "SS", img: "CMatsuokaCasual_R3.png" },
  { id: "ss097", name: "[懲惡的英勇動作戲]松岡 綺羅路", rarity: "SS", img: "CMatsuokaActor_R3.png" },
  { id: "ss155", name: "[寒光劍影]夏目 祈", rarity: "SS", img: "INatsumeDefault_R3.png" },
  { id: "ss098", name: "[衣鄉夢蝶]夏目 祈", rarity: "SS", img: "INatsumeButterfly_R3.png" },
  { id: "ss099", name: "[芳華青金石]夏目 祈", rarity: "SS", img: "INatsumeNeat_R3.png" },
  { id: "ss156", name: "[紀念日的風馳電擊]黑澤 真希", rarity: "SS", img: "MKurosawaDefault_R3.png" },
  { id: "ss100", name: "[青翠疾風走死走愛]黑澤 真希", rarity: "SS", img: "MKurosawaCasual_R3.png" },
  { id: "ss157", name: "[摩天樓的暗黑英雄]卡羅爾•利帕", rarity: "SS", img: "CReaperDefault_R3.png" },
  { id: "ss101", name: "[Carnival with You]卡羅爾•利帕", rarity: "SS", img: "CReaperDate_R3.png" },
  { id: "ss102", name: "[Heve ni fear!i'm a hero!]卡羅爾•利帕", rarity: "SS", img: "CReaperWhiteSuit_R3.png" },
  { id: "ss158", name: "[吾不勇 與無將同]李 映夏", rarity: "SS", img: "LShanhuaDefault_R3.png" },
  { id: "ss103", name: "[引路一襲露草色]李 映夏", rarity: "SS", img: "LShanhuaNoble_R3.png" },
  { id: "ss104", name: "[春宵我愛你]李 映夏", rarity: "SS", img: "LShanhuaSuspicious_R3.png" },
  { id: "ss159", name: "[藍色石榴石探索]艾琳•雷德梅因", rarity: "SS", img: "IRedmayneDefault_R3.png" },
  { id: "ss105", name: "[月下的追迷藏]艾琳•雷德梅因", rarity: "SS", img: "IRedmaynePhantom_R3.png" },
  { id: "ss106", name: "[頌歌的微風所向]艾琳•雷德梅因", rarity: "SS", img: "IRedmayneIdyllic_R3.png" },
  { id: "ss160", name: "[凜然的杜爾迦]芙里提卡•巴拉克里希南", rarity: "SS", img: "VBalakrishnanDefault_R3.png" },
  { id: "ss107", name: "[美麗的聖虎]芙里提卡•巴拉克里希南", rarity: "SS", img: "VBalakrishnanTradition_R3.png" },
  { id: "ss108", name: "[款待的安納布爾納]芙里提卡•巴拉克里希南", rarity: "SS", img: "VBalakrishnanKitchen_R3.png" },
  { id: "ss161", name: "[血色浮雕]瑪麗亞•黛•安傑利斯", rarity: "SS", img: "MdAngelisDefault_R3.png" },
  { id: "ss109", name: "[剎那的邂逅]瑪麗亞•黛•安傑利斯", rarity: "SS", img: "MdAngelisKnights_R3.png" },
  { id: "ss110", name: "[優雅假期]瑪麗亞•黛•安傑利斯", rarity: "SS", img: "MdAngelisMafia_R3.png" },
  { id: "ss111", name: "[永久的思念]夏洛特•斯可波夫斯加", rarity: "SS", img: "CSkopovskayaVampire_R3.png" },
  { id: "ss112", name: "[聖潔新娘]夏洛特•斯可波夫斯加", rarity: "SS", img: "CSkopovskayaBride_R3.png" },
  { id: "ss113", name: "[獻上愛的晚餐]夏洛特•斯可波夫斯加", rarity: "SS", img: "CSkopovskayaKitchen_R3.png" },
  { id: "ss162", name: "[逆境盛放之花]夏洛特•斯可波夫斯加", rarity: "SS", img: "CSkopovskayaDefault_R3.png" }
];